# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy main

on:
  push:
    branches: [ "main" ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Docker Build Tag Publish
      uses: bitovi/github-actions-docker-publish@v1.0.2
      with:
        image_tag: latest_main
        repo_name: bb2002/specialfunc-api:tagname
        docker_username: bb2002
        docker_password: dckr_pat_tavOkn-afoH6iMpb6Om-ekZPiVA
    
    
