export enum ESPFuncStatusCode {
  EXCEED_APPLICATION_COUNT = 'A100',
  ENDPOINT_ALREADY_EXIST = 'A101',

  UNREGISTERED_ACCOUNT = 'U100',
  BLOCKED_ACCOUNT = 'U101',
  USER_NOT_FOUND_EXCEPTION = 'U102',
}
